[package]
name = "minigrep_tupelo"
version = "0.1.0"
edition = "2021"
description = "test"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
